# Generated by Django 5.2.6 on 2025-09-16 08:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_query', models.TextField()),
                ('bot_response', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('differential_diagnoses', models.JSONField(blank=True, default=list)),
                ('risk_assessment', models.JSONField(blank=True, default=dict)),
                ('semantic_analysis', models.JSONField(blank=True, default=dict)),
                ('enhanced_response', models.JSONField(blank=True, default=dict)),
                ('medical_summary', models.JSONField(blank=True, default=dict)),
                ('qa_results', models.JSONField(blank=True, default=list)),
                ('llm_features_used', models.JSONField(blank=True, default=dict)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_queries', models.IntegerField(default=0)),
                ('successful_analyses', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('semantic_analysis_used', models.IntegerField(default=0)),
                ('dense_retrieval_used', models.IntegerField(default=0)),
                ('text_summarization_used', models.IntegerField(default=0)),
                ('qa_system_used', models.IntegerField(default=0)),
                ('enhanced_rag_used', models.IntegerField(default=0)),
                ('top_medical_entities', models.JSONField(blank=True, default=list)),
                ('common_diagnoses', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='MedicalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_text', models.CharField(max_length=200)),
                ('umls_cui', models.CharField(blank=True, max_length=20, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='Rag.chatsession')),
            ],
        ),
    ]
